services:
  mysql:
    image: mysql:8
    container_name: rental_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rental
      MYSQL_USER: rental_user
      MYSQL_PASSWORD: nhuy0600
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu MySQL
      - ./rental_db.sql:/docker-entrypoint-initdb.d/rental_db.sql  # Tự động restore nếu có

volumes:
  mysql_data:
